language: node
services:
  - docker
before_install:
  # Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service 
  # Use either `docker-compose` or individual `docker build` commands 
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./reverseproxy
  # Tagging
  - docker tag udagram-api-feed tainguyen90/udagram-api-feed:v1
  - docker tag udagram-api-user tainguyen90/udagram-api-user:v1
  - docker tag udagram-frontend tainguyen90/udagram-frontend:v1
  - docker tag reverseproxy tainguyen90/reverseproxy:v1
  # Push
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tainguyen90/udagram-api-feed:v1
  - docker push tainguyen90/udagram-api-user:v1
  - docker push tainguyen90/udagram-frontend:v1
  - docker push tainguyen90/reverseproxy:v1